/*
 * Port_cfg.h
 *
 *  Created on: Mar 16, 2022
 *      Author: U3
 */

#ifndef PORT_CFG_H_
#define PORT_CFG_H_


/**/
#define PORT_PIN_0_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_1_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_2_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_3_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_4_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_5_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_6_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_7_INIT_CFG	      OUTPUT_LOW
#define PORT_PIN_8_INIT_CFG	      OUTPUT_HIGH
#define PORT_PIN_9_INIT_CFG	      OUTPUT_HIGH
#define PORT_PIN_10_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_11_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_12_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_13_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_14_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_15_INIT_CFG	  OUTPUT_HIGH
#define PORT_PIN_16_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_17_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_18_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_19_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_20_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_21_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_22_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_23_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_24_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_25_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_26_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_27_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_28_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_29_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_30_INIT_CFG	  OUTPUT_LOW
#define PORT_PIN_31_INIT_CFG	  OUTPUT_LOW


#define INPUT_PULLUP			0
#define INPUT_HIGH_IMPEDENCE	1
#define OUTPUT_LOW				2
#define OUTPUT_HIGH				3


#endif /* PORT_CFG_H_ */
